
import { Book } from './types';

export const BIBLE_BOOKS: Book[] = [
  { name: '创世记 Genesis', id: 'GEN', chapters: 50 },
  { name: '出埃及记 Exodus', id: 'EXO', chapters: 40 },
  { name: '利未记 Leviticus', id: 'LEV', chapters: 27 },
  { name: '民数记 Numbers', id: 'NUM', chapters: 36 },
  { name: '申命记 Deuteronomy', id: 'DEU', chapters: 34 },
  { name: '约书亚记 Joshua', id: 'JOS', chapters: 24 },
  { name: '士师记 Judges', id: 'JDG', chapters: 21 },
  { name: '路得记 Ruth', id: 'RUT', chapters: 4 },
  { name: '撒母耳记上 1 Samuel', id: '1SA', chapters: 31 },
  { name: '撒母耳记下 2 Samuel', id: '2SA', chapters: 24 },
  { name: '列王纪上 1 Kings', id: '1KI', chapters: 22 },
  { name: '列王纪下 2 Kings', id: '2KI', chapters: 25 },
  { name: '历代志上 1 Chronicles', id: '1CH', chapters: 29 },
  { name: '历代志下 2 Chronicles', id: '2CH', chapters: 36 },
  { name: '以斯拉记 Ezra', id: 'EZR', chapters: 10 },
  { name: '尼希米记 Nehemiah', id: 'NEH', chapters: 13 },
  { name: '以斯帖记 Esther', id: 'EST', chapters: 10 },
  { name: '约伯记 Job', id: 'JOB', chapters: 42 },
  { name: '诗篇 Psalms', id: 'PSA', chapters: 150 },
  { name: '箴言 Proverbs', id: 'PRO', chapters: 31 },
  { name: '传道书 Ecclesiastes', id: 'ECC', chapters: 12 },
  { name: '雅歌 Song of Solomon', id: 'SNG', chapters: 8 },
  { name: '以赛亚书 Isaiah', id: 'ISA', chapters: 66 },
  { name: '耶利米书 Jeremiah', id: 'JER', chapters: 52 },
  { name: '耶利米哀歌 Lamentations', id: 'LAM', chapters: 5 },
  { name: '以西结书 Ezekiel', id: 'EZK', chapters: 48 },
  { name: '但以理书 Daniel', id: 'DAN', chapters: 12 },
  { name: '何西阿书 Hosea', id: 'HOS', chapters: 14 },
  { name: '约珥书 Joel', id: 'JOE', chapters: 3 },
  { name: '阿摩司书 Amos', id: 'AMO', chapters: 9 },
  { name: '俄巴底亚书 Obadiah', id: 'OBA', chapters: 1 },
  { name: '约拿书 Jonah', id: 'JON', chapters: 4 },
  { name: '弥迦书 Micah', id: 'MIC', chapters: 7 },
  { name: '那鸿书 Nahum', id: 'NAM', chapters: 3 },
  { name: '哈巴谷书 Habakkuk', id: 'HAB', chapters: 3 },
  { name: '西番雅书 Zephaniah', id: 'ZEP', chapters: 3 },
  { name: '哈该书 Haggai', id: 'HAG', chapters: 2 },
  { name: '撒迦利亚书 Zechariah', id: 'ZEC', chapters: 14 },
  { name: '玛拉基书 Malachi', id: 'MAL', chapters: 4 },
  { name: '马太福音 Matthew', id: 'MAT', chapters: 28 },
  { name: '马可福音 Mark', id: 'MRK', chapters: 16 },
  { name: '路加福音 Luke', id: 'LUK', chapters: 24 },
  { name: '约翰福音 John', id: 'JHN', chapters: 21 },
  { name: '使徒行传 Acts', id: 'ACT', chapters: 28 },
  { name: '罗马书 Romans', id: 'ROM', chapters: 16 },
  { name: '哥林多前书 1 Corinthians', id: '1CO', chapters: 16 },
  { name: '哥林多后书 2 Corinthians', id: '2CO', chapters: 13 },
  { name: '加拉太书 Galatians', id: 'GAL', chapters: 6 },
  { name: '以弗所书 Ephesians', id: 'EPH', chapters: 6 },
  { name: '腓立比书 Philippians', id: 'PHP', chapters: 4 },
  { name: '歌罗西书 Colossians', id: 'COL', chapters: 4 },
  { name: '帖撒罗尼迦前书 1 Thessalonians', id: '1TH', chapters: 5 },
  { name: '帖撒罗尼迦后书 2 Thessalonians', id: '2TH', chapters: 3 },
  { name: '提摩太前书 1 Timothy', id: '1TI', chapters: 6 },
  { name: '提摩太后书 2 Timothy', id: '2TI', chapters: 4 },
  { name: '提多书 Titus', id: 'TIT', chapters: 3 },
  { name: '腓利门书 Philemon', id: 'PHM', chapters: 1 },
  { name: '希伯来书 Hebrews', id: 'HEB', chapters: 13 },
  { name: '雅各书 James', id: 'JAS', chapters: 5 },
  { name: '彼得前书 1 Peter', id: '1PE', chapters: 5 },
  { name: '彼得后书 2 Peter', id: '2PE', chapters: 3 },
  { name: '约翰一书 1 John', id: '1JN', chapters: 5 },
  { name: '约翰二书 2 John', id: '2JN', chapters: 1 },
  { name: '约翰三书 3 John', id: '3JN', chapters: 1 },
  { name: '犹大书 Jude', id: 'JUD', chapters: 1 },
  { name: '启示录 Revelation', id: 'REV', chapters: 22 },
];
